CREATE TABLE "access_control" (
  "user_id" varchar,
  "post_id" integer,
  "access_status" varchar
);

CREATE TABLE "invalid_tokens" (
  "id" integer PRIMARY KEY NOT NULL,
  "token" text,
  "user_id" varchar
);

CREATE TABLE "tabs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "post_id" integer,
  "title" varchar,
  "icon" text,
  "url" text
);

CREATE TABLE "users" (
  "id" varchar PRIMARY KEY,
  "email" varchar,
  "auth_provider" varchar,
  "name" varchar,
  "password" varchar,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "alarm_status" boolean,
  "alarm_time" varchar,
  "alarm_days" jsonb[] DEFAULT ARRAY['{"day": "sun", "value": false}'::jsonb, '{"day": "mon", "value": true}'::jsonb, '{"day": "tue", "value": true}'::jsonb, '{"day": "wed", "value": true}'::jsonb, '{"day": "thu", "value": true}'::jsonb, '{"day": "fri", "value": true}'::jsonb, '{"day": "sat", "value": false}'::jsonb],
);

CREATE TABLE "transcribe_log" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" varchar,
  "date" timestamp DEFAULT (CURRENT_TIMESTAMP WITH TIMEZONE),
  "count" integer
);

CREATE TABLE "posts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" varchar,
  "date" date,
  "summary_text" text,
  "summary_voice" bytea,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "last_updated" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "tags" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "post_id" integer,
  "text" varchar
);

CREATE TABLE "shared_posts" (
  "id" varchar PRIMARY KEY,
  "pointer_id" varchar,
  "post_id" integer,
  "shared_at" timestamp DEFAULT (CURRENT_TIMESTAMP)
);

COMMENT ON COLUMN "access_control"."access_status" IS 'read-only or read-write';

COMMENT ON COLUMN "posts"."summary_text" IS 'This should be your EOD notes. What happened today.';

ALTER TABLE "posts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "invalid_tokens" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "access_control" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "access_control" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id");

ALTER TABLE "transcribe_log" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "tabs" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id");

ALTER TABLE "shared_posts" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id");

ALTER TABLE "tags" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id");
